"""Clean-install smoke test.

This test boots ``examples/fastapi-minimal/main.py`` in-process via
``httpx.ASGITransport`` and exercises the full intake → storage roundtrip
that a fresh ``pip install bug-fab`` consumer would do as their first
verification step.

Why a separate smoke test in addition to the existing submit/viewer
integration suites:

* The other integration tests pin individual routes against the
  ``app_factory`` fixture. This one boots the *example app* the way a
  consumer's deployment would, so it catches packaging regressions —
  missing static files, wrong path resolution, broken
  ``importlib.resources`` lookups, etc.
* It runs entirely in-process (no port binding, no subprocess) so it's
  reproducible in CI and doesn't race against the dev server.
* It exercises the post-2026-04-29 spec-tightening fields
  (``protocol_version``, ``client_ts``, ``reporter``) end-to-end.

The test was added 2026-04-30 to replace the bash-script smoke test
that broke during the 2026-04-29 clean-venv verification (CV5 in the
audit). The pytest version is reproducible and CI-friendly.
"""

from __future__ import annotations

import importlib.util
import struct
import sys
import zlib
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
EXAMPLE_MAIN_PATH = REPO_ROOT / "examples" / "fastapi-minimal" / "main.py"


def _make_minimal_png() -> bytes:
    """Hand-rolled valid 1x1 PNG (single transparent pixel).

    Inline implementation rather than re-using ``conftest.py`` helpers so
    the smoke test doesn't depend on cross-suite fixture machinery — a
    fresh-install consumer wouldn't have access to those fixtures
    either.
    """
    sig = b"\x89PNG\r\n\x1a\n"
    ihdr_data = struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)
    ihdr = (
        struct.pack(">I", len(ihdr_data))
        + b"IHDR"
        + ihdr_data
        + struct.pack(">I", zlib.crc32(b"IHDR" + ihdr_data) & 0xFFFFFFFF)
    )
    raw = b"\x00\x00\x00\x00\x00"  # filter byte + RGBA pixel
    idat_data = zlib.compress(raw)
    idat = (
        struct.pack(">I", len(idat_data))
        + b"IDAT"
        + idat_data
        + struct.pack(">I", zlib.crc32(b"IDAT" + idat_data) & 0xFFFFFFFF)
    )
    iend = struct.pack(">I", 0) + b"IEND" + struct.pack(">I", zlib.crc32(b"IEND") & 0xFFFFFFFF)
    return sig + ihdr + idat + iend


def _load_example_app(tmp_path: Path):
    """Import ``examples/fastapi-minimal/main.py`` via importlib.

    The example uses module-level state (a ``STORAGE_DIR`` constant that
    becomes the on-disk root). We override it before calling
    ``create_app()`` so each test gets a fresh storage directory and
    nothing leaks between runs.
    """
    spec = importlib.util.spec_from_file_location("bug_fab_example_main", EXAMPLE_MAIN_PATH)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise RuntimeError(f"Could not load example main from {EXAMPLE_MAIN_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["bug_fab_example_main"] = module
    spec.loader.exec_module(module)
    module.STORAGE_DIR = tmp_path / "bug_reports"
    return module.create_app()


@pytest.mark.integration
def test_example_app_full_roundtrip(tmp_path: Path) -> None:
    """Boot the fastapi-minimal example, submit a report, verify storage.

    Replicates what a consumer's first ``python main.py`` boot + first
    bug submission looks like end-to-end. Uses FastAPI's synchronous
    ``TestClient`` (which wraps an ASGI transport internally) so the
    test runs without ``pytest-asyncio`` or other async plugins.
    """
    app = _load_example_app(tmp_path)

    with TestClient(app) as client:
        # The home page should serve the demo HTML.
        home_response = client.get("/")
        assert home_response.status_code == 200
        assert "BugFab" in home_response.text

        # Submit a bug report — full v0.1 wire-protocol shape.
        metadata = {
            "protocol_version": "0.1",
            "title": "Smoke test: example app handles fresh-install roundtrip",
            "client_ts": "2026-04-30T12:00:00+00:00",
            "report_type": "bug",
            "description": "Generated by tests/integration/test_clean_install_smoke.py",
            "expected_behavior": "Full request/storage/response cycle completes.",
            "severity": "low",
            "tags": ["smoke", "ci"],
            "reporter": {"name": "smoke-test", "email": "", "user_id": ""},
            "context": {
                "url": "http://testhost/",
                "module": "smoke",
                "user_agent": "pytest-asgi/1.0",
                "viewport_width": 1024,
                "viewport_height": 768,
                "console_errors": [],
                "network_log": [],
                "app_version": "0.1.0a1",
                "environment": "test",
            },
        }

        files = {
            "metadata": (None, _serialize_metadata(metadata)),
            "screenshot": ("smoke.png", _make_minimal_png(), "image/png"),
        }
        submit_response = client.post("/api/bug-reports", files=files)
        assert submit_response.status_code == 201, submit_response.text
        body = submit_response.json()
        assert body["id"].startswith("bug-")
        assert body["github_issue_url"] is None

        # Round-trip: the viewer's JSON list should now show one report.
        list_response = client.get("/admin/bug-reports/reports")
        assert list_response.status_code == 200
        listing = list_response.json()
        assert listing["total"] == 1
        assert listing["items"][0]["id"] == body["id"]
        assert listing["items"][0]["title"].startswith("Smoke test:")

        # Detail fetch should return the full submitted shape, including
        # the new spec-tightening fields.
        detail_response = client.get(f"/admin/bug-reports/reports/{body['id']}")
        assert detail_response.status_code == 200
        detail = detail_response.json()
        assert detail["protocol_version"] == "0.1"
        assert detail["client_ts"] == "2026-04-30T12:00:00+00:00"
        assert detail["reporter"]["name"] == "smoke-test"
        assert detail["context"]["module"] == "smoke"
        # Server-captured user-agent — set by the route from the request
        # header. The TestClient sets a synthetic user-agent, so we only
        # assert the field is present and non-empty.
        assert isinstance(detail["server_user_agent"], str)


def _serialize_metadata(metadata: dict) -> str:
    """JSON-encode the metadata dict for the multipart 'metadata' part.

    Inline import of ``json`` because the test should work even if a
    consumer's environment has ``orjson`` or similar shadowing the stdlib.
    """
    import json

    return json.dumps(metadata)
