// <auto-generated />
using System;
using BugFab.AspNetCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BugFab.AspNetCore.Data.Migrations
{
    [DbContext(typeof(BugFabDbContext))]
    partial class BugFabDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("BugFab.AspNetCore.Data.Entities.BugFabIdCounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("LastValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_value");

                    b.HasKey("Id");

                    b.ToTable("bug_fab_id_counter");
                });

            modelBuilder.Entity("BugFab.AspNetCore.Data.Entities.BugReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AppName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("app_name");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("archived_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Environment")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("environment");

                    b.Property<int?>("GitHubIssueNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("github_issue_number");

                    b.Property<string>("GitHubIssueUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("github_issue_url");

                    b.Property<long>("IdSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_sequence");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Module")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("module");

                    b.Property<string>("PageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("page_url");

                    b.Property<string>("ProtocolVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol_version");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("received_at");

                    b.Property<string>("Reporter")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("reporter");

                    b.Property<string>("ScreenshotPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("screenshot_path");

                    b.Property<string>("Severity")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("UserAgentClient")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent_client");

                    b.Property<string>("UserAgentServer")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent_server");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedAt")
                        .HasDatabaseName("idx_bug_fab_archived_at");

                    b.HasIndex("Environment")
                        .HasDatabaseName("idx_bug_fab_environment");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("idx_bug_fab_received_at");

                    b.HasIndex("Severity")
                        .HasDatabaseName("idx_bug_fab_severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_bug_fab_status");

                    b.ToTable("bug_fab_bug_reports");
                });

            modelBuilder.Entity("BugFab.AspNetCore.Data.Entities.BugReportLifecycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("TEXT")
                        .HasColumnName("at");

                    b.Property<string>("BugReportId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("bug_report_id");

                    b.Property<string>("By")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("by");

                    b.Property<string>("FixCommit")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("fix_commit");

                    b.Property<string>("FixDescription")
                        .HasColumnType("TEXT")
                        .HasColumnName("fix_description");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("Status")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("BugReportId")
                        .HasDatabaseName("idx_bug_fab_lifecycle_report_id");

                    b.ToTable("bug_fab_bug_report_lifecycle");
                });

            modelBuilder.Entity("BugFab.AspNetCore.Data.Entities.BugReportLifecycle", b =>
                {
                    b.HasOne("BugFab.AspNetCore.Data.Entities.BugReport", "BugReport")
                        .WithMany("Lifecycle")
                        .HasForeignKey("BugReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BugReport");
                });

            modelBuilder.Entity("BugFab.AspNetCore.Data.Entities.BugReport", b =>
                {
                    b.Navigation("Lifecycle");
                });
#pragma warning restore 612, 618
        }
    }
}
